--------------------------------------------------------
--  File created - Friday-September-11-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HCCLASS
--------------------------------------------------------

  CREATE TABLE "TESTDB"."HCCLASS" 
   (	"CRN" NUMBER, 
	"COURSENUM" NUMBER, 
	"INSTRUCTORID" NUMBER, 
	"CLASSROOMNUM" NUMBER, 
	"SEMESTER" VARCHAR2(20 BYTE), 
	"DAYTIME" VARCHAR2(50 BYTE), 
	"ENABLE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HCCLASSROOM
--------------------------------------------------------

  CREATE TABLE "TESTDB"."HCCLASSROOM" 
   (	"ID" NUMBER, 
	"BLDGNAME" VARCHAR2(100 BYTE), 
	"ROOM" NUMBER, 
	"MAXCAP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HCCOURSE
--------------------------------------------------------

  CREATE TABLE "TESTDB"."HCCOURSE" 
   (	"COURSENUM" NUMBER, 
	"SUBJECTCODE" VARCHAR2(20 BYTE), 
	"DESCR" VARCHAR2(2000 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"CREDITS" NUMBER, 
	"DEPARTMENTID" NUMBER, 
	"ENABLE" NUMBER, 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HCDEPT
--------------------------------------------------------

  CREATE TABLE "TESTDB"."HCDEPT" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"ENABLE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HCENROLLEDCLASS
--------------------------------------------------------

  CREATE TABLE "TESTDB"."HCENROLLEDCLASS" 
   (	"ID" NUMBER, 
	"STUDENTID" NUMBER, 
	"CLASSID" NUMBER, 
	"GRADE" NUMBER, 
	"SEMESTER" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HCMOJOR
--------------------------------------------------------

  CREATE TABLE "TESTDB"."HCMOJOR" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"ENABLE" NUMBER, 
	"DEPTID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HCUSERS
--------------------------------------------------------

  CREATE TABLE "TESTDB"."HCUSERS" 
   (	"USERID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"MAJORID" NUMBER, 
	"ENTRYDATE" VARCHAR2(20 BYTE), 
	"DEPTID" NUMBER, 
	"OFFICENUM" NUMBER, 
	"TYPE" NUMBER, 
	"PASSWORD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TESTDB.HCCLASS
SET DEFINE OFF;
REM INSERTING into TESTDB.HCCLASSROOM
SET DEFINE OFF;
REM INSERTING into TESTDB.HCCOURSE
SET DEFINE OFF;
REM INSERTING into TESTDB.HCDEPT
SET DEFINE OFF;
REM INSERTING into TESTDB.HCENROLLEDCLASS
SET DEFINE OFF;
REM INSERTING into TESTDB.HCMOJOR
SET DEFINE OFF;
REM INSERTING into TESTDB.HCUSERS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index HCCLASS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."HCCLASS_PK" ON "TESTDB"."HCCLASS" ("CRN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HCCLASSROOM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."HCCLASSROOM_PK" ON "TESTDB"."HCCLASSROOM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HCCOURSE_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."HCCOURSE_PK1" ON "TESTDB"."HCCOURSE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HCDEPT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."HCDEPT_PK" ON "TESTDB"."HCDEPT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HCENROLLED_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."HCENROLLED_PK" ON "TESTDB"."HCENROLLEDCLASS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HCMOJOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."HCMOJOR_PK" ON "TESTDB"."HCMOJOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HCUSERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."HCUSERS_PK" ON "TESTDB"."HCUSERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table HCCLASS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."HCCLASS" ADD CONSTRAINT "HCCLASS_PK" PRIMARY KEY ("CRN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."HCCLASS" MODIFY ("CRN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HCCLASSROOM
--------------------------------------------------------

  ALTER TABLE "TESTDB"."HCCLASSROOM" ADD CONSTRAINT "HCCLASSROOM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."HCCLASSROOM" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HCCOURSE
--------------------------------------------------------

  ALTER TABLE "TESTDB"."HCCOURSE" ADD CONSTRAINT "HCCOURSE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."HCCOURSE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TESTDB"."HCCOURSE" MODIFY ("SUBJECTCODE" NOT NULL ENABLE);
  ALTER TABLE "TESTDB"."HCCOURSE" MODIFY ("COURSENUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HCDEPT
--------------------------------------------------------

  ALTER TABLE "TESTDB"."HCDEPT" ADD CONSTRAINT "HCDEPT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."HCDEPT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HCENROLLEDCLASS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."HCENROLLEDCLASS" ADD CONSTRAINT "HCENROLLED_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."HCENROLLEDCLASS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HCMOJOR
--------------------------------------------------------

  ALTER TABLE "TESTDB"."HCMOJOR" ADD CONSTRAINT "HCMOJOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."HCMOJOR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HCUSERS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."HCUSERS" ADD CONSTRAINT "HCUSERS_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."HCUSERS" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table HCCLASS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."HCCLASS" ADD CONSTRAINT "CLASSROOM_FK" FOREIGN KEY ("CLASSROOMNUM")
	  REFERENCES "TESTDB"."HCCLASSROOM" ("ID") ENABLE;
  ALTER TABLE "TESTDB"."HCCLASS" ADD CONSTRAINT "COURSE_FK" FOREIGN KEY ("COURSENUM")
	  REFERENCES "TESTDB"."HCCOURSE" ("ID") ENABLE;
  ALTER TABLE "TESTDB"."HCCLASS" ADD CONSTRAINT "INSTRUTOR_FK" FOREIGN KEY ("INSTRUCTORID")
	  REFERENCES "TESTDB"."HCUSERS" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HCCOURSE
--------------------------------------------------------

  ALTER TABLE "TESTDB"."HCCOURSE" ADD CONSTRAINT "DEPARTMENT_FK" FOREIGN KEY ("DEPARTMENTID")
	  REFERENCES "TESTDB"."HCDEPT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HCENROLLEDCLASS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."HCENROLLEDCLASS" ADD CONSTRAINT "CLASSID_FK" FOREIGN KEY ("CLASSID")
	  REFERENCES "TESTDB"."HCCLASS" ("CRN") ENABLE;
  ALTER TABLE "TESTDB"."HCENROLLEDCLASS" ADD CONSTRAINT "STUDENTID_FK" FOREIGN KEY ("STUDENTID")
	  REFERENCES "TESTDB"."HCUSERS" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HCMOJOR
--------------------------------------------------------

  ALTER TABLE "TESTDB"."HCMOJOR" ADD CONSTRAINT "DEP_FK" FOREIGN KEY ("DEPTID")
	  REFERENCES "TESTDB"."HCDEPT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HCUSERS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."HCUSERS" ADD CONSTRAINT "DEPARTMENTID_FK" FOREIGN KEY ("DEPTID")
	  REFERENCES "TESTDB"."HCDEPT" ("ID") ENABLE;
  ALTER TABLE "TESTDB"."HCUSERS" ADD CONSTRAINT "MAJOR_FK" FOREIGN KEY ("MAJORID")
	  REFERENCES "TESTDB"."HCMOJOR" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCCLASS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."HCCLASS_TRG" 
BEFORE INSERT ON HCCLASS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."HCCLASS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCCLASS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."HCCLASS_TRG1" 
BEFORE INSERT ON HCCLASS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT HCCLASS_SEQ1.NEXTVAL INTO :NEW.CRN FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."HCCLASS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCCLASSROOM_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."HCCLASSROOM_TRG" 
BEFORE INSERT ON HCCLASSROOM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT HCCLASSROOM_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."HCCLASSROOM_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCCOURSE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."HCCOURSE_TRG" 
BEFORE INSERT ON HCCOURSE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."HCCOURSE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCCOURSE_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."HCCOURSE_TRG1" 
BEFORE INSERT ON HCCOURSE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT HCCOURSE_SEQ1.NEXTVAL INTO :NEW.COURSENUM FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."HCCOURSE_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCDEPT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."HCDEPT_TRG" 
BEFORE INSERT ON HCDEPT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT HCDEPT_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."HCDEPT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCENROLLEDCLASS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."HCENROLLEDCLASS_TRG" 
BEFORE INSERT ON HCENROLLEDCLASS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT HCENROLLEDCLASS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."HCENROLLEDCLASS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCMOJOR_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."HCMOJOR_TRG" 
BEFORE INSERT ON HCMOJOR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT HCMOJOR_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."HCMOJOR_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCUSERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."HCUSERS_TRG" 
BEFORE INSERT ON HCUSERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT HCUSERS_SEQ.NEXTVAL INTO :NEW.USERID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."HCUSERS_TRG" ENABLE;
